version: '3'
services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: 'rabbitmq_container'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks: 
      - myanimegalaxy_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  myanimegalaxy_sql:
    container_name: myanimegalaxy_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyEnaPassword0
      - MSSQL_PID=Developer
    ports:
      - 1405:1433
    expose:
      - 1433
    networks:
      - myanimegalaxy_network

  myanimegalaxy_api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=myanimegalaxy_sql,1433;Database=200027;User=sa;Password=MyEnaPassword0;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetcore-devcert.pfx
      - STRIPE_API_KEY=sk_test_51PdbM8Rsmg17KngzOLAbX3R0nBEkCCTMKKdraMetVJiuoOL3aQqv0Wqj00dn1tkET4znbZvqI9nCeYMH6OLTfxm600Qzmua2Xt
    ports:
      - "7074:7074"
    networks:
      - myanimegalaxy_network
    links:
      - myanimegalaxy_sql
    depends_on:
      - myanimegalaxy_sql
      - rabbitMQ
    volumes:
      - ./aspnetcore-devcert.pfx:/root/.aspnet/https/aspnetcore-devcert.pfx
      - ./SeedImages:/app/SeedImages

  rabbitmq-consumer:
    restart: unless-stopped
    build:
      context: ./RabbitMQConsumer
    environment:
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=myanimegalaxy0@gmail.com
      - SMTP_PASSWORD=ltkdhzwgcznbeonf
    depends_on:
      - myanimegalaxy_sql
      - myanimegalaxy_api
      - rabbitMQ
    networks:
      - myanimegalaxy_network

volumes:
  rabbitmq_data:

networks:
  myanimegalaxy_network:
    driver: bridge
